docs/modules/ROOT/nav.adoc, docs/modules/examples/pages/flare.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/langchain-evaluation.adoc
* Add docs, index, nav, and colab link for evaluation notebook.
=> Docs - Add LangChain evaluator notebook

RELEASE.md, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/changelog.adoc, scripts/generate-changelog.py
* Added script to generate the requirements table for a specific ragstack-ai version. Only some dependencies are kept 
* Added page to the doc with the changelog
=> [RAG-11] Add RAGStack changelog

README.md
=> [RAG-86] Docs - update readme

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/changelog.adoc
* Move changelog in nav
* Add github releases and pypi index to changelog page
=> Docs: move changelog nav and add links

examples/notebooks/quickstart.ipynb
Moves the quickstart notebook over
=> [RAG-75] docs: add quickstart notebook

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/migration.adoc
Documentation for LangChain migration.
=> [RAG-40] - Docs - langchain migration

examples/notebooks/FLARE.ipynb, examples/notebooks/advancedRAG.ipynb, examples/notebooks/langchain_evaluation.ipynb, examples/notebooks/quickstart.ipynb
Fix broken run links in notebooks.
=> Docs - fix links in notebooks

docs/modules/ROOT/nav.adoc, docs/modules/examples/pages/advanced-rag.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/langchain-evaluation.adoc, docs/modules/examples/partials/prerequisites.adoc
* Add advanced RAG notebook content to docs. 
* openai_key in prerequisites changed to openai_api_key where used.
* Add to nav and index.
=> Docs - add advanced rag 

docs/modules/ROOT/nav.adoc, docs/modules/examples/pages/advanced-rag.adoc
.API Reference
* https://datastax.github.io/ragstack-ai/api_reference/0.4.0/langchain[0.4.0]
* https://datastax.github.io/ragstack-ai/api_reference/0.3.1/langchain[0.3.1]
=> Docs- add API ref to nav

docs/modules/ROOT/nav.adoc, docs/modules/default-architecture/pages/index.adoc
=> Docs - nav and index patch

docs/modules/ROOT/nav.adoc
=> Docs - bump nav to 0.5.0

.github/workflows/ci.yml, examples/notebooks/QA_with_cassio.ipynb, examples/notebooks/RAG_with_cassio.ipynb
Simplifies and updates the cassio notebooks
=> docs: update cassio notebooks 

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/prerequisites.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/langchain_multimodal_gemini.adoc
* Add Gemini notebook to nav and examples page
* Add gemini notebook to doc (conversion test run)
=> [docs] Add gemini notebook

examples/notebooks/nvidia.ipynb, examples/notebooks/quickstart.ipynb
Adds basic rag notebook with NVIDIA models.
=> [notebooks] add basic rag notebook using nvidia models

docs/modules/ROOT/pages/tests.adoc
Unordered list syntax cleanup.
=> Docs - Update tests.adoc

ragstack-e2e-tests/benchmarks/testcases.py, ragstack-e2e-tests/e2e_tests/langchain/rag_application.py, ragstack-e2e-tests/e2e_tests/langchain/test_compatibility_rag.py, ragstack-e2e-tests/e2e_tests/langchain/trulens.py, ragstack-e2e-tests/pyproject.langchain.toml, ragstack-e2e-tests/pyproject.toml
Adds TruLens evaluation to the test matrix.
=> [tests] add trulens to test matrix

docs/modules/examples/pages/llama-astra.adoc
Add colab badge now that notebook is working.
=> [Docs] - Update llama-astra.adoc

docs/modules/ROOT/nav.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/mmr.adoc, docs/modules/examples/partials/mmr-example.adoc, examples/notebooks/cqlsession.py, examples/notebooks/llm_choice.py, examples/notebooks/qa-maximal-marginal-relevance.ipynb
* Adapt [this example ](https://cassio.org/frameworks/langchain/qa-maximal-marginal-relevance/) to ragstack and document it. 
* Works
`(mmr-test) ➜  mmr-notebook-test python3 mmr-test-final.py
92113d9999ad463a8ad6aef0b2181f70
840d924b3870412cbf1101a0f6da0e02
0a4977930c134df2a11d798c42470792
57cd5e3560824500a4b7f2e242191742
2d9d171d704c48c89cc81e9812008391
Similarity-based chain:
ANSWER : The party was thrown by all the toads and frogs under the moon that night.
SOURCES: Barney's story at the pub
MMR-based chain:
ANSWER : The party that night was thrown by the frogs and toads, and the rule was for everyone to wear a purple hat.
SOURCES: Barney's story at the pub, The chronicles at the village library`
=> [RAG-178] - Docs - MMR 

docs/modules/ROOT/nav.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/mmr.adoc, examples/notebooks/qa-maximal-marginal-relevance.ipynb
* Update ci badge in nav
* *MMR links
=> Docs - patch nav and mmr links

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/dev-environment.adoc, docs/modules/ROOT/pages/migration.adoc, docs/modules/ROOT/pages/quickstart.adoc, docs/modules/ROOT/pages/tests.adoc, docs/modules/default-architecture/pages/generation.adoc, docs/modules/default-architecture/pages/index.adoc, docs/modules/default-architecture/pages/loading.adoc, docs/modules/default-architecture/pages/retrieval.adoc, docs/modules/default-architecture/pages/splitting.adoc, docs/modules/default-architecture/pages/storing.adoc, docs/modules/examples/pages/advanced-rag.adoc, docs/modules/examples/pages/flare.adoc, docs/modules/examples/pages/langchain-evaluation.adoc, docs/modules/examples/pages/langchain_multimodal_gemini.adoc, docs/modules/examples/pages/llama-astra.adoc, docs/modules/examples/pages/mmr.adoc, docs/modules/examples/pages/nvidia_embeddings.adoc, docs/modules/examples/pages/qa-with-cassio.adoc, docs/modules/examples/pages/rag-with-cassio.adoc, docs/modules/intro-to-rag/pages/advanced-rag.adoc, docs/modules/intro-to-rag/pages/evaluating.adoc, docs/modules/intro-to-rag/pages/index.adoc, docs/modules/intro-to-rag/pages/indexing.adoc, docs/modules/intro-to-rag/pages/querying.adoc
* Check links
* Enforce google style guide
=> [RAG 181] - Docs - Check links and enforce styleguide

docs/modules/ROOT/pages/dev-environment.adoc, docs/modules/ROOT/pages/prerequisites.adoc, docs/modules/default-architecture/pages/retrieval.adoc, docs/modules/intro-to-rag/pages/advanced-rag.adoc, docs/modules/intro-to-rag/pages/evaluating.adoc, docs/modules/intro-to-rag/pages/indexing.adoc, docs/modules/intro-to-rag/pages/querying.adoc
=> [Docs] - Capitalize headings

README.adoc, docs/modules/ROOT/nav.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/llama-parse-astra.adoc
* RAG pattern for quickstart from @erichare's notebook using local env and removing asyncio
* Added notebook to nav, examples index
* Fixed snyk badge in readme
* Split examples page by framework and client so it's not just a long table
* Added a step to print a node for verification
=> [RAG-198] - Docs - LlamaParse

scripts/generate-api-reference.sh
to merge if this passes: https://github.com/datastax/ragstack-ai/actions/runs/8296024218
=> ci: fix api reference build

ragstack-e2e-tests/e2e_tests/llama_index/test_compatibility_rag.py
Forgot to disable llama gpt4 tests in previous PR.
=> [tests] temporarily disable GPT4 tests for llama too

ragstack-e2e-tests/e2e_tests/langchain/test_compatibility_rag.py
=> [tests] add single gpt4 test back

ragstack-e2e-tests/e2e_tests/langchain/test_compatibility_rag.py
=> [tests] disable gpt4 tests again

pyproject.toml, ragstack/colbert/__init__.py, ragstack/colbert/cassandra_retriever.py, ragstack/colbert/cassandra_store.py, ragstack/colbert/colbert_embedding.py, ragstack/colbert/langchain/__init__.py, ragstack/colbert/langchain/retriever.py, ragstack/colbert/token_embedding.py, ragstack/colbert/vector_store.py
Adds mypy and fixes a bunch of type issues.
Not every issue is fixed by this PR yet so atm mypy is not enforced in CI.
=> Add mypy for type checking

tests/unit_tests/test_colbert_baseline_embeddings.py
Support the colbert embedding support other colbert models
=> compatibility test to support other colbert models

ragstack/colbert/colbert_embedding.py, tests/unit_tests/test_colbert_retriever.py
reduce paddings on query_maxlen in the default setting although user can still specify the query_maxlen
=> reduce paddings on query_maxlen in the default setting

.github/workflows/ci-e2e-tests.yml
Reduces test frequency to once per day (staggered, still). 
Closes [#282 ](https://datastax.jira.com/browse/RAG-282)
=> [CI]: Update test frequency to 1/day

ragstack-e2e-tests/e2e_tests/langchain/test_compatibility_rag.py
This change postpones the initialization of the llms and embedding objects. This allows us to do things like check the config for nemo guardrails to skip the test before attempting init. 
Previously, if the init failed, we weren't correctly skipping the `nemo` test, meaning they were displayed as failing within testspace, rather than automatically skipping them as expected.
=> [tests]: change fixtures to functions

ragstack/colbert/__init__.py, ragstack/colbert/llamaindex/__init__.py, ragstack/colbert/llamaindex/retriever.py, tests/integration_tests/test_colbert_embedding_retrieval.py
this is written for LlamaIndex > 0.10.0 which isn't in ragstack yet :(
=> added a llamaIndex ColBERT retriever

docs/modules/ROOT/pages/quickstart.adoc
Corrected the full code sample (the snippets were previously corrected).
RAG-289
=> Update quickstart.adoc to correct the full code sample

libs/e2e-tests/pyproject.llamaindex.toml, libs/tests-utils/pyproject.toml
latest release of `requests` broke docker-py: https://github.com/psf/requests/issues/6707
=> ci: fix test with docker

libs/e2e-tests/e2e_tests/langchain/conftest.py, libs/e2e-tests/e2e_tests/langchain/test_cassandra_tool.py, libs/e2e-tests/e2e_tests/langchain/test_unstructured.py, libs/e2e-tests/pyproject.langchain.toml, libs/e2e-tests/pyproject.llamaindex.toml, libs/e2e-tests/pyproject.ragstack-ai.toml, libs/e2e-tests/pyproject.toml
it was already imported as part of langchain community
=> feat: add langchain cassandra tool

docs/modules/ROOT/nav.adoc, docs/modules/ragstack-ts/pages/quickstart.adoc
=> Docs-fix-build-errors

docs/modules/ROOT/nav.adoc, docs/modules/ragstack-ts/pages/quickstart.adoc
* Cleanup quickstart page
* Add changelog to nav
=> Docs update ts quickstart and nav

libs/knowledge-store/notebooks/astra_support.ipynb, libs/knowledge-store/ragstack_knowledge_store/base.py, libs/knowledge-store/ragstack_knowledge_store/cassandra.py, libs/knowledge-store/tests/test_knowledge_store.py
This creates a demo notebook that loads the Astra
docs into a KnowledgeStore with edges inferred
from links in the content.
This revealed a bug in the directed edge extractor which is fixed.
=> [knowledge store] docs: Astra Docs Demo

docs/modules/examples/pages/hotels-app.adoc, docs/modules/examples/pages/index.adoc
- Repo moved to Datastax-Examples GH org
- instructions updated to the ragstack-native latest version of the app
- uses a convenient cleanup oneliner
- a few typos and adaptations to the latest flow
=> docs: updates to the "Hotels app" page

docs/modules/ROOT/pages/quickstart.adoc
OPEN_AI_API_KEY -> OPENAI_API_KEY
=> [Docs] - Update openai key in quickstart.adoc
