.github/workflows/ci.yml
https://github.com/datastax/ragstack-ai/pull/134/files requires the langchain API key, but CI needs to know about it first before those notebook tests pass
=> CI: Add LC api key to CI secrets

ragstack-e2e-tests/e2e_tests/langchain/test_astra.py, ragstack-e2e-tests/e2e_tests/llama_index/test_astra.py
Summary:
- port the first half of tests from langchain/test_astra.py to LlamaIndex
One interesting difference between LlamaIndex and LangChain is that by default LlamaIndex performs text splitting, so the tests about "errors due to long texts" are different
=> [RAG-103] Init AstraDB LlamaIndex tests

docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/qa-with-cassio.adoc, docs/modules/examples/pages/rag-with-cassio.adoc, examples/notebooks/QA_with_cassio.ipynb, examples/notebooks/RAG_with_cassio.ipynb
Old paths were still pointing to the examples repo. This adds them here and fixes the documentation links (@mendonk please verify that's all the places that need fixing)
This, for now, fixes so they at least have a notebook. Some of the techniques in this notebook(s) are outdated, so I'll clean them up on the next PR.
=> docs: add rag/qa with cassio notebooks

ragstack-e2e-tests/e2e_tests/langchain/test_compatibility_rag.py, ragstack-e2e-tests/e2e_tests/llama_index/test_compatibility_rag.py
They're failing more often. The problem seems in the google-vertex client, I opened this issue: https://github.com/googleapis/python-aiplatform/issues/3227
=> tests: temporary disable vertex gemini pro tests

.github/actions/deploy-slack-report/action.yml, .github/actions/setup-python/action.yml, .github/workflows/ci.yml, .github/workflows/clean-astra-env.yml, .github/workflows/deploy-docker.yml, .github/workflows/langchain-master-daily.yml, .github/workflows/llamaindex-main-daily.yml, .github/workflows/ragstack-ai-latest.yml, .github/workflows/release-ragstack.yml, .github/workflows/run-benchmarks.yml, .github/workflows/security-scans.yml, .github/workflows/update-pages.yml
Fix the following warnings
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, slackapi/slack-github-action@v1.24.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> ci: update some plugins

ragstack-e2e-tests/e2e_tests/langchain/test_astra.py, ragstack-e2e-tests/e2e_tests/llama_index/test_astra.py
Unless they changed the status error being returned, I'm not quite sure why it was previously working as a `ValueError`.
=> [tests] use HTTPStatusError instead of ValueError

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/migration.adoc, docs/modules/ROOT/pages/prerequisites.adoc
* Bump version in nav and migration
* Add llamaindex cloud API key to prerequisites
=> [docs] - Bump API to 0.7.0

docs/modules/examples/pages/llama-parse-astra.adoc
Llama-parse is part of ragstack-ai as of 0.7.0, no need to install
=> [Docs] - Remove llama-parse dependency

examples/notebooks/llama-parse-astra.ipynb
This updates the llama parse example notebook to be compatible with the latest 0.10.x release of llama.
=> Update Llama Parse Notebook for llama 0.10.x

.github/workflows/ci-unit-tests.yml, pyproject.toml
```
The current project's supported Python range (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
[249](https://github.com/datastax/ragstack-ai/actions/runs/8081337583/job/22079661904#step:4:252)
- unstructured requires Python >=3.9.0,<3.12, so it will not be satisfied for Python >=3.12,<4.0
```
=> change py range to <3.12

.github/workflows/ci-e2e-tests.yml, .github/workflows/ci-unit-tests.yml
docs-only changes make the CI to be skipped (and it's fine) but the GH checks required to a PR to be merged aren't completed in this way. 
For usability, it's way better to run unit tests and have the PR green. 
there are alternatives to this approach, like checking a single job result that is computed dinamically, but it's not worth it. let's run the unit tests always
=> ci: run unit tests even for docs only change

ragstack-e2e-tests/e2e_tests/langchain/test_compatibility_rag.py
We've noticed high levels of gpt4 api usage, resulting in high costs. Temporarily commenting these out until we can reduce the frequency of different test suites.
=> [tests] temporarily disable GPT4 tests

ragstack/colbert/__init__.py, ragstack/colbert/cassandra_retriever.py, ragstack/colbert/cassandra_store.py, ragstack/colbert/colbert_embedding.py, ragstack/colbert/langchain/__init__.py, ragstack/colbert/langchain/retriever.py, ragstack/colbert/token_embedding.py, ragstack/colbert/vector_store.py, tests/integration_tests/test_colbert_embedding_retrieval.py, tests/unit_tests/test_colbert_embeddings.py
ColBERT should not require a `title` for each document. It should be an optional `id`, that is generated if not passed.
If a developer wants to save the `filename` or other `title` for a document, they should do it in the metadata.
This PR is in place of https://github.com/datastax/ragstack-ai/pull/338
Also made a bunch of other name changes.
=> replaced "title" with "id" for ColBERT document identifier

ragstack/colbert/cassandra_retriever.py, ragstack/colbert/chunk_encoder.py, ragstack/colbert/colbert_embedding.py, ragstack/colbert/runner.py, tests/integration_tests/test_colbert_embedding_retrieval.py
made a bunch of changes that generally make sure our ColBERT retrieval code interacts nicely with Cassandra (doesn't overload the database when making queries). 
There is little change in retrieval latency with these changes running on CPU.
* wrapped async calls to cassandra inside a `ThreadPoolExecutor`.  
* We should experiment to see what value of `max_casandra_workers` works the best.
* automatically dropping down to half-precision when calculating chunk scores, if running on GPU and the GPU supports it.  
* We should test to see if `is_fp16` flag is getting set to `True` on boxes with CUDA support. 
* I "think" that half-precision won't hurt our results, and chatGPT claims this can "significantly speed up our calculations & reduce memory usage on the GPU".
=> made various changes to cleanup retrieval

.github/workflows/dispatch-deploy-draft.yml, docs/modules/ROOT/pages/changelog.adoc
Upgrading to ragstack-ai 1.0.0 changes the llamaindex version from 0.9.x to 0.10.x which has breaking changes. 
Added a note and a link to the official llamaindex documentation for the migration guide
=> docs: add note about llamaindex upgrade

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/packages.adoc, docs/modules/langflow/pages/index.adoc
Index page with dependencies, install, and link to more quickstarts.
=> Docs - RAGStack x Langflow

docs/modules/ROOT/nav.adoc
as discussed with @mendonk let's remove the out-of-date toc for the api reference. 
All the links are available in the changelog page too
=> docs: remove api reference from toc

libs/colbert/ragstack_colbert/base_vector_store.py, libs/colbert/ragstack_colbert/cassandra_database.py
the synchronous code was using asynchronous methods behind the scenes, and would create many errors on large insertions. This reverts the synchronous methods back to synchronous code.
=> fixed colbert db sync methods

libs/knowledge-store/README.md, libs/knowledge-store/pyproject.toml, libs/knowledge-store/ragstack_knowledge_store/concurrency.py, libs/knowledge-store/ragstack_knowledge_store/content.py, libs/knowledge-store/ragstack_knowledge_store/knowledge_store.py, libs/knowledge-store/tests/conftest.py, libs/knowledge-store/tests/test_knowledge_store.py
- Improved concurrency of keyword linking.
- HREF->URL linking.
- Update README with more details on how to use.
Other changes:
- Use `python-dotenv` to load `.env` to simplify test execution.
- Remove pinned `requests` since `docker` has fixed the issue.
=> feat: Pull in knowledge store improvements

libs/knowledge-store/ragstack_knowledge_store/concurrency.py, libs/knowledge-store/ragstack_knowledge_store/content.py, libs/knowledge-store/ragstack_knowledge_store/knowledge_store.py, libs/knowledge-store/tests/conftest.py, libs/knowledge-store/tests/test_knowledge_store.py
This should speed up traversals by issuing the queries for nodes/edges/ids concurrently.
=> feat: knowlege-store concurrent traversal

libs/knowledge-graph/pyproject.toml, libs/knowledge-graph/tests/conftest.py, libs/knowledge-graph/tests/test_extraction.py, libs/knowledge-graph/tests/test_knowledge_graph.py, libs/knowledge-graph/tests/test_runnables.py, libs/knowledge-graph/tests/test_traverse.py, libs/knowledge-graph/tox.ini, libs/knowledge-store/pyproject.toml, libs/knowledge-store/tests/test_knowledge_store.py
Though `precisely` can probably bring nice Harmcrest-like assertions, it's easy to replace its `contains_exactly` by a mere `sorted` + `==` (pytest will output a nice diff).
LangChain doesn't use precisely so introducing a dependency lib will be harder when we move the tests there.
So it's better to reduce the number of libs we drag for the moment.
=> Remove dependency on precisely

docs/modules/ROOT/pages/quickstart.adoc, docs/modules/ROOT/pages/what-is-rag.adoc, docs/modules/examples/pages/advanced-rag.adoc, docs/modules/examples/pages/colbert.adoc, docs/modules/examples/pages/flare.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/langchain-evaluation.adoc, docs/modules/examples/pages/langchain-unstructured-astra.adoc, docs/modules/examples/pages/langchain_multimodal_gemini.adoc, docs/modules/examples/pages/llama-astra.adoc, docs/modules/examples/pages/llama-parse-astra.adoc, docs/modules/examples/pages/mmr.adoc, docs/modules/examples/pages/nvidia_embeddings.adoc, docs/modules/examples/pages/qa-with-cassio.adoc, docs/modules/examples/pages/rag-with-cassio.adoc
Moving to the new docs site broke image links.
This PR fixes it.
=> [RAG-366] Fix Docs Colab links

docs/modules/examples/pages/mmr.adoc, docs/modules/examples/partials/mmr-example.adoc
The "VectorStore QA with MMR" page is showing usage of the `Cassandra` vector store class.
This PR switches the page to using the `AstraDBVectorStore`, i.e. the Data API connector, keeping everything else as it was.
In particular:
- change in the env vars (endpoint in place of db id)
- remove note on how to extract db id from endpoint
- change in the var name for the v.store variable and how it is initialized
- changes reflected to the separate `mmr-example.adoc` file.
**NOTE** the "open in colab" link at the top is still pointing to the Cassandra version of the same workload ... because the code I'm contributing is not hosted as a colab-friendly notebook anywhere. I can add it if desired, but then I'd suggest the location to be a colab/notebook dedicated directory inside _this_ repo …
=> (docs) MMR page switch to AstraDBVectorStore (=data api)

libs/knowledge-store/ragstack_knowledge_store/graph_store.py
This denormalizes the outgoing tags into the `links` table, so that
traversal doesn't need to fetch the set of outgoing tags in an initial
query. This means that traversing is one batch of concurrent queries,
rather than two steps in sequence.
This lowers average retrieval time in 6 experiments from 1.3364s to
1.0920s (would increase as more nodes are retrieved). Writing the
additional copies of the denormalized tags adds a little to indexing
time.
=> feat: Reduce sequential queries for MMR

docs/local-preview-playbook.yml, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/changelog.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/luna-for-ragstack.adoc, docs/modules/ROOT/pages/prerequisites.adoc, docs/modules/default-architecture/pages/loading.adoc, docs/modules/examples/pages/dse-69.adoc, docs/modules/examples/pages/hcd.adoc, docs/modules/examples/pages/index.adoc, docs/modules/examples/pages/langchain_multimodal_gemini.adoc, docs/modules/examples/pages/prerequisites.adoc, docs/modules/examples/pages/qa-with-cassio.adoc, docs/modules/examples/pages/rag-with-cassio.adoc, docs/modules/examples/partials/prerequisites.adoc, docs/modules/langflow/pages/index.adoc, docs/modules/ragstack-ts/pages/changelog.adoc, docs/package-lock.json, docs/package.json
The HCD and DSE 6.9 examples needed to be added to the nav. I updated some external links to comply with our updated style guidelines.
@mendonk Do these pages also need to be added to the [examples index](https://github.com/datastax/ragstack-ai/blob/main/docs/modules/examples/pages/index.adoc)? Also, while making this change, I noticed that there is an orphan page that needs to be dealt with: https://datastax.jira.com/browse/DOC-4477
=> Add HCD and DSE 6.9 examples to nav

libs/knowledge-store/notebooks/astra_support.ipynb, libs/knowledge-store/ragstack_knowledge_store/graph_store.py, libs/knowledge-store/tests/integration_tests/test_graph_store.py, libs/langchain/ragstack_langchain/graph_store/cassandra.py, libs/langchain/tests/integration_tests/test_graph_store.py
This seems to be unnecessary. An SAI index supporting contains seems to be sufficient. Eliminating it removes the need to create the denormalized copy of the data, speeding up insertion and reducing storage needs.
=> feat: Eliminate the targets table

libs/langchain/ragstack_langchain/colbert/colbert_vector_store.py
It's important to respect the `as_retriever` signature as some LangChain components use it and expect a `VectorStoreRetriever`.
=> Fix ColbertVectorStore as_retriever()

libs/knowledge-store/ragstack_knowledge_store/graph_store.py, libs/knowledge-store/tests/integration_tests/test_graph_store.py
This adds a `neighborhood` parameter to the mmr_traversal, and starts the search with the best candidates adjacent to the provided `neighborhood`.
=> feat: mmr traversal starting in neighborhood

docs/modules/examples/pages/hotels-app.adoc, docs/modules/examples/pages/langchain-unstructured-astra.adoc, docs/modules/examples/pages/llama-astra.adoc, docs/modules/examples/pages/llama-parse-astra.adoc, docs/modules/examples/pages/mmr.adoc, docs/modules/examples/pages/nvidia_embeddings.adoc, examples/notebooks/FLARE.ipynb, examples/notebooks/advancedRAG.ipynb, examples/notebooks/langchain_evaluation.ipynb, examples/notebooks/langchain_multimodal_gemini.ipynb, examples/notebooks/llama-astra.ipynb, examples/notebooks/nemo_guardrails.ipynb, examples/notebooks/nvidia.ipynb, examples/notebooks/quickstart.ipynb
[Address broken links](https://github.com/riptano/astra-vector-docs/issues/549)
=> Fix prerequisites link

libs/knowledge-store/ragstack_knowledge_store/_mmr_helper.py, libs/knowledge-store/ragstack_knowledge_store/graph_store.py, libs/knowledge-store/tests/unit_tests/test_mmr_helper.py
=> feat: add scores to MMR results

libs/knowledge-store/notebooks/astra_support.ipynb
Adding IMPORTANT banner at the top of astra_support.ipynb that redirects to the new graph-rag project.
=> Adding redirect message to graph RAG notebook
